In [1]:
# Data Science Library Numpy
import numpy as np

In [2]:
myarr=np.array([1,2,3,4,6,5,7],np.int8)
myarr

array([1, 2, 3, 4, 6, 5, 7], dtype=int8)

In [3]:
myarr[1]

2

In [4]:
myarr.shape

(7,)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[3]=88
myarr

array([ 1,  2,  3, 88,  6,  5,  7], dtype=int8)

In [7]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.dtype

dtype('int64')

In [9]:
listarray.shape

(3, 3)

In [10]:
np.array({1,1,1})

array({1}, dtype=object)

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# linspace function is used to create linearly spaced array(start,end,spaced)
lspace=np.linspace(1,50,10)

In [14]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [15]:
# emp will make an empty array with random no.s
emp=np.empty((4,6))
emp

array([[0.00000000e+000, 2.41907520e-312, 1.29441743e-312,
        2.37663529e-312, 2.05833592e-312, 2.41907520e-312],
       [2.56761491e-312, 1.93101617e-312, 9.33678148e-313,
        9.33678148e-313, 9.33678148e-313, 9.33678148e-313],
       [9.33678148e-313, 9.33678148e-313, 1.97345609e-312,
        2.33419537e-312, 9.76118064e-313, 2.33419537e-312],
       [1.18831764e-312, 2.12199579e-313, 2.56761491e-312,
        2.41907520e-312, 5.63234836e-322, 0.00000000e+000]])

In [16]:
#empty like
# it makes empty array like
emp_like=np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
ide=np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a=np.arange(99)

In [19]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
a.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
#opposite of reshape is ravel
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
# axis 0 is row axis 1 is column
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
x.sum(axis=0)

array([12, 15, 18])

In [24]:
x.sum(axis=1)

array([ 6, 15, 24])

In [25]:
#Tranpose means row to col & col to row
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
x.flat

In [27]:
# flat is used to flatten an array
for i in x.flat:
  print(i)

1
2
3
4
5
6
7
8
9


In [28]:
x.ndim

2

In [29]:
x.size

9

In [30]:
x.nbytes

72

In [31]:
one=np.array([1,2,3,4])
one.argmax()

3

In [32]:
one.argsort()

array([0, 1, 2, 3])

In [33]:
# matrix multiplication
ar2=np.array([[1,2,3],[4,5,6],[8,9,0]])
ar2+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 10,  1]])

In [34]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.82842712, 3.        , 0.        ]])

In [35]:
ar2.max()

9

In [36]:
np.where(ar2>5)

(array([1, 2, 2]), array([2, 0, 1]))

In [37]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [38]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)
  


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [39]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
  
newarr = arr.reshape(2, 2, 3)
  
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)
  


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [40]:
# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(arr, axis = 0, kind = 'mergesort'))
  

Column wise sort by applying merge-sort:
 [[1 2 0 1]
 [1 2 3 2]
 [5 2 4 4]]


In [41]:
"""
The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. 
A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

"""
# Python Programming illustrating
# numpy.eye method

import numpy as geek

# 2x2 matrix with 1's on main diagnol
b = geek.eye(2, dtype = float)
print("Matrix b : \n", b)

# matrix with R=4 C=5 and 1 on diagnol
# below main diagnol
a = geek.eye(4, 5, k = -1)
print("\nMatrix a : \n", a)


Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [42]:
# import numpy
import numpy as np

# using numpy.core.fromrecords() method
gfg = np.core.records.fromrecords([(101, 'Jitender', 21),
									(102, 'Deepak', 20)],
							names = 'Rollno, Name, Age')

print(gfg[0])


(101, 'Jitender', 21)


In [43]:
# importing the module
import numpy as np

# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)


Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]
